### PR TITLE
Node.js Support

### PR DESCRIPTION
**Pull request by marshall007**
Sorry for the massive PR, but it was difficult to break this up into small pieces.

#### Changes

- Refactored each plugin into it's own module (no longer modifies globals)
- Added test and build scripts (use `npm test` and `npm run build` respectively)
- Added Node.js support while maintaining browser support (using `browserify`)
  - Running `npm run build` writes the browser bundle to `./dist/knwl.js`
- Running tests no longer requires globally installed npm packages
- Plugins are now registered explicitly using `knwl.register(name, definition)`
  - All default plugins are automatically registered for you
- Renamed `knwl.parserList` to `knwl.plugins`

#### Todo

- Update docs to reflect these changes.
- Make sure everything in the demo still works as expected.

Let me know if you have any issues with what I've done here. I'm happy to update this PR.

### CODE REVIEW

**Comment by loadfive** [comment]
Hi! This looks excellent. But there seems to be a problem with ```npm build``` and ```npm test```

Here's the output from ```npm test```:
```console

scripts/test.sh

scripts/test.sh: line 1: ./node_modules/.bin/jasmine-node: No such file or directory
npm ERR! Test failed.  See above for more details.

```

There seems to be a problem with ```npm build```, too. Though there are no apparent error messages, no files are created if they do not exist in the ```./dist``` directory.

**Comment by marshall007** [comment]
@loadfive did you run `npm install` to get the dependencies first?

**Comment by loadfive** [comment]
After running ```npm install```, the command ```npm test``` runs without errors. Sorry for that overlook. :-)

One down, but even after running ```npm install```, ```npm build``` fails to create the directory ```./dist``` if does not exist. If the directory does exist, it still seems to fail to create any files within.

**Comment by marshall007** [comment]
Ah, sorry I was mistaken. It looks like `npm build` is actually an actual command so it doesn't alias to `npm run build` like `npm test` does. You should be able to do `npm run build` though.

**Comment by loadfive** [comment]
That fixed the issue! The only other thing is plugins. The simpler they can be to deploy on the client-side and server-side, the better. Is there a straightforward way of adding a third-party plugin (written as a Node.js module) to Knwl.js on the client-side?

**Comment by thebergamo** [comment]
Using broserify the plugins used on browsers can do more powerful things! This is an excellent issue!

**Comment by marshall007** [comment]
@loadfive if they are using `browserify` then registering third-party plugins would be the same in both Node.js and the browser:

```js
var knwl = require('knwl');
knwl.register('custom', require('knwl-custom-plugin'));
```

**Comment by thebergamo** [comment]
+1 @marshall007 its amazing if you update the readme.md show how the new colaborators can use it!

**Comment by loadfive** [comment]
@marshall007 Great! The new documentation is almost finished. Will merge as soon as possible.

**Comment by loadfive** [comment]
If there's a file, say ```demo.js``` in the Knwl.js directory, that has these contents:

```javascript
var knwl = require("./knwl.js");
knwl.register('todos', require('./default_plugins/testPlugin.js'));
```

Assuming the plugin existed, using browserify, what command would be best for you run in the terminal to package that for the browser? Thanks and sorry for this little hassle. This PR is really great, just trying to get the documentation together.

**Comment by marshall007** [comment]
@loadfive I'm not sure I understand what you're asking, but you could do `./node_modules/.bin/browserify demo.js > output.js`. There shouldn't be a reason to explain this in the documentation though. I think `knwl` should be published to `npm` and `bower` and the user's build process should be independent of what we're doing.

**Comment by loadfive** [comment]
Excellent. Merging the pull request. Again, sorry for the delay. Will push the new documentation as well.

**Comment by marshall007** [comment]
Sweet, no worries! Are you planning on publishing to `npm`? It's pretty important for Node.js users. You can have Travis automatically publish tagged releases automatically ([see docs](http://docs.travis-ci.com/user/deployment/npm/)).

**Comment by loadfive** [comment]
Just pushed it to ```npm```:
```console
npm install knwl.js
```

And I'll look into having Travis automatically push new releases.

**Pull request merged**
